[[edge_functions]]
function = "get-blob-data"
path = "/api/get-blob-data"

[dev]
edge_functions = "apps/some-web-app/netlify/edge-functions"

[build]
edge_functions = "apps/some-web-app/netlify/edge-functions"
